// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn27L30P6lRT4SatVVtx6kc5s94MrW2O0',
    appId: '1:9107631260:web:06f1068419670cba319159',
    messagingSenderId: '9107631260',
    projectId: 'ethical-fitness',
    authDomain: 'ethical-fitness.firebaseapp.com',
    databaseURL: 'https://ethical-fitness-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ethical-fitness.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArfWPn4UREjJwWOlexMQ1A71tvp6_bvy0',
    appId: '1:9107631260:android:3fd5029d8d35a468319159',
    messagingSenderId: '9107631260',
    projectId: 'ethical-fitness',
    databaseURL: 'https://ethical-fitness-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ethical-fitness.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb70BnfthLGQ0--_mixSq3keJNFxR3Vwo',
    appId: '1:9107631260:ios:6351e5a189bb5a27319159',
    messagingSenderId: '9107631260',
    projectId: 'ethical-fitness',
    databaseURL: 'https://ethical-fitness-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ethical-fitness.appspot.com',
    iosClientId: '9107631260-cjdbfjpj0svbahpanq16am8ccj3794rv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ethicalfitness2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb70BnfthLGQ0--_mixSq3keJNFxR3Vwo',
    appId: '1:9107631260:ios:6351e5a189bb5a27319159',
    messagingSenderId: '9107631260',
    projectId: 'ethical-fitness',
    databaseURL: 'https://ethical-fitness-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ethical-fitness.appspot.com',
    iosClientId: '9107631260-cjdbfjpj0svbahpanq16am8ccj3794rv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ethicalfitness2',
  );
}
